# -*- coding: utf-8 -*-
"""
Indice (libreria) delle applicazioni eseguibili del PC.

Alla prima richiesta (e poi al piu' una volta ogni REFRESH_SECONDI) raccoglie:
  1. collegamenti .lnk del menu Start (utente + comune) e del desktop
  2. app Microsoft Store / AppX via PowerShell Get-StartApps (inclusi i loro alias)
  3. eseguibili .exe portabili in cartelle tipiche (nessuna voce nel registro)

Tutto finisce in una libreria unica cercabile per nome, salvata in cache su
%LOCALAPPDATA%/chicco/app_index.json e passabile all'LLM come contesto.
"""
import json
import os
import re
import shutil
import subprocess
import threading
import time
import unicodedata
from pathlib import Path

try:
    from . import platform_utils as pu
except ImportError:  # importato come modulo top-level (server avviato come script)
    import platform_utils as pu

REFRESH_SECONDI = 600  # rescan al piu' ogni 10 minuti
BASE = pu.data_dir()
INDEX_FILE = BASE / "app_index.json"
_lock = threading.Lock()
_cache = {"when": 0.0, "apps": []}


def _norm(s: str) -> str:
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", " ", s.lower()).strip()


# ---------------------------------------------------------------------------
# 1) collegamenti .lnk
# ---------------------------------------------------------------------------
def _lnk_dirs() -> list:
    """Sorgenti dei collegamenti: Start Menu su Windows, /Applications e .desktop su mac/Linux."""
    dirs = []
    if pu.IS_WINDOWS:
        for env in ("APPDATA", "PROGRAMDATA"):
            base = os.environ.get(env)
            if base:
                p = Path(base) / "Microsoft" / "Windows" / "Start Menu" / "Programs"
                if p.is_dir():
                    dirs.append(p)
        for d in (Path.home() / "Desktop",
                  Path(os.environ.get("PUBLIC", "")) / "Desktop"):
            if d.is_dir():
                dirs.append(d)
    elif pu.IS_MAC:
        for d in (Path("/Applications"), Path.home() / "Applications"):
            if d.is_dir():
                dirs.append(d)
    else:
        for d in (Path.home() / ".local" / "share" / "applications",
                  Path("/usr") / "share" / "applications",
                  Path("/usr") / "local" / "share" / "applications"):
            if d.is_dir():
                dirs.append(d)
    return dirs


def _collect_lnks() -> list:
    apps = []
    for d in _lnk_dirs():
        try:
            if pu.IS_WINDOWS:
                for f in d.rglob("*.lnk"):
                    apps.append({"name": f.stem, "kind": "lnk", "target": str(f)})
            elif pu.IS_MAC:
                for app in d.glob("*.app"):
                    apps.append({"name": app.stem, "kind": "macapp", "target": str(app)})
            else:
                for f in d.glob("*.desktop"):
                    if f.stem.startswith("."):
                        continue
                    apps.append({"name": f.stem, "kind": "desktop", "target": str(f)})
        except Exception:
            pass
    return apps


# ---------------------------------------------------------------------------
# 2) Microsoft Store / AppX via Get-StartApps
# ---------------------------------------------------------------------------
def _collect_startapps() -> list:
    if not pu.IS_WINDOWS:
        return []  # Get-StartApps esiste solo su Windows
    out = []
    try:
        r = subprocess.run(
            ["powershell", "-NoProfile", "-Command",
             "Get-StartApps | ForEach-Object { \"$($_.Name)|$($_.AppID)\" }"],
            capture_output=True, text=True, timeout=60,
            creationflags=subprocess.CREATE_NO_WINDOW)
        for line in (r.stdout or "").splitlines():
            if "|" not in line:
                continue
            name, appid = line.rsplit("|", 1)
            name = name.strip()
            appid = appid.strip()
            if not name or not appid:
                continue
            if appid.startswith("Microsoft.AutoGenerated"):
                continue  # entri fisiche, non azioni (es. "Impostazioni|control")
            kind = "appx" if "!" in appid else "shell"
            out.append({"name": name, "kind": kind, "target": appid})
    except Exception:
        pass
    return out


# ---------------------------------------------------------------------------
# 3) eseguibili portabili (cartelle tipiche, senza registro)
# ---------------------------------------------------------------------------
def _portable_roots() -> list:
    roots = []
    if pu.IS_WINDOWS:
        for env in ("LOCALAPPDATA", "APPDATA", "PROGRAMFILES", "PROGRAMFILES(X86)"):
            base = os.environ.get(env)
            if base:
                roots.append(Path(base) / "Programs")
        for extra in (Path.home() / "Portable Programs",
                      Path("D:/") / "Programs", Path("D:/") / "Portable"):
            if extra.is_dir():
                roots.append(extra)
    elif pu.IS_MAC:
        for extra in (Path.home() / "Applications", Path("/opt") / "homebrew"):
            if extra.is_dir():
                roots.append(extra)
    else:
        for extra in (Path.home() / ".local" / "opt", Path("/opt"),
                      Path.home() / "opt"):
            if extra.is_dir():
                roots.append(extra)
    return roots


def _collect_portables() -> list:
    apps, seen_exe = [], set()
    pattern = "*.exe" if pu.IS_WINDOWS else "*.AppImage"
    for root in _portable_roots():
        if not root.is_dir():
            continue
        try:
            it = root.rglob(pattern)
        except Exception:
            continue
        for exe in it:
            low = exe.name.lower()
            # scarta disinstallatori, crash reporter, ecc.
            if any(k in low for k in ("unins", "uninstall", "crash", "updater",
                                      "setup", "helper", "crashpad")):
                continue
            if exe.name in seen_exe:
                continue
            seen_exe.add(exe.name)
            apps.append({"name": exe.stem, "kind": "portable", "target": str(exe)})
    return apps


# ---------------------------------------------------------------------------
# dedup + scoring
# ---------------------------------------------------------------------------
def _dedupe(apps: list) -> list:
    best: dict = {}
    for a in apps:
        key = _norm(a["name"])
        if not key:
            continue
        rank = {"lnk": 3, "appx": 2, "portable": 1, "shell": 1}.get(a["kind"], 1)
        cur = best.get(key)
        if cur is None or rank > {"lnk": 3, "appx": 2, "portable": 1, "shell": 1}.get(cur["kind"], 1):
            best[key] = a
    return sorted(best.values(), key=lambda a: a["name"].lower())


def build_index() -> list:
    apps = _collect_lnks() + _collect_startapps() + _collect_portables()
    apps = _dedupe(apps)
    try:
        BASE.mkdir(parents=True, exist_ok=True)
        INDEX_FILE.write_text(json.dumps(apps, ensure_ascii=False), encoding="utf-8")
    except Exception:
        pass
    return apps


def get_apps(force: bool = False) -> list:
    """Libreria corrente; rescan lazy se vecchia o vuota (thread-safe)."""
    with _lock:
        stale = time.time() - _cache["when"] > REFRESH_SECONDI
        if force or not _cache["apps"] or stale:
            try:
                _cache["apps"] = build_index()
            except Exception:
                _cache["apps"] = []
            _cache["when"] = time.time()
        return _cache["apps"]


def scan_async() -> None:
    """Avvia la scansione in background (chiamato all'avvio del server)."""
    threading.Thread(target=get_apps, daemon=True).start()


def search(query: str, limit: int = 15) -> list:
    """Cerca app per nome: match esatto > contiene > sottostringa."""
    t = _norm(query)
    if not t:
        return []
    scored = []
    for a in get_apps():
        n = _norm(a["name"])
        if n == t:
            s = 4.0
        elif n.startswith(t):
            s = 3.0 + min(1.0, len(t) / max(1, len(n)))
        elif t in n:
            s = 2.0 + min(1.0, len(t) / max(1, len(n)))
        elif all(w in n for w in t.split()):
            s = 1.5
        else:
            s = 0.0
        if s > 0:
            scored.append((s, a))
    scored.sort(key=lambda x: (-x[0], x[1]["name"].lower()))
    return [a for _, a in scored[:limit]]


def launch(app: dict) -> None:
    """Avvia un'app dell'indice secondo il suo tipo."""
    kind, target = app["kind"], app["target"]
    if pu.IS_WINDOWS:
        if kind in ("appx", "shell"):
            subprocess.Popen(["explorer.exe", target])
        else:  # lnk o portable
            os.startfile(target)  # noqa: S606
    elif kind == "macapp":
        subprocess.Popen(["open", target])
    elif kind == "desktop":
        subprocess.Popen(["gio", "launch", target] if shutil.which("gio") else ["sh", target])
    else:
        pu.open_path(target)


def llm_context(limit: int = 120) -> str:
    """Lista compatta dei nomi, da dare in contesto all'LLM."""
    names = [a["name"] for a in get_apps()[:limit]]
    return "; ".join(names)
